units           real
atom_style      full
boundary        p p p

pair_style      lj/cut 12.500 
bond_style      harmonic
angle_style     hybrid cosine/periodic fourier
dihedral_style   harmonic 
improper_style  fourier

dielectric      1.0
pair_modify     tail yes mix arithmetic
special_bonds   lj/coul 0.0 0.0 1.0
#kspace_style    ewald/disp 0.0001
#neigh_modify every 1 delay 0 check yes


###Atom grouping
#group fram id 1:3456
#group fram1 id 3456:3468
